pegasystems/pega-datascientist-tools

README.md, python/cdh_utils.py
Translation of cdh_utils.R in Python (cdh_utils.py)
=> Implemented cdh_utils for Python

python/model_report.py
two python classes. One class reports on models including historical performance. The other class reports on the latest model and their predictors
=> python code to generate reports and graphs given ADM mart data

r/R/adm.R, r/tests/testthat/test_adm.R
Added a convenience function to find the active score range and bin indices so to more easily calculate real AUC or other metrics for the active bins of a classifier
=> Support finding active range in classifiers through a convenience fun

examples/hds/Example_Data_Anonymization.ipynb, python/pdstools/plots/plot_base.py
Reverted path appending changes, hidden cells are still hidden
=> Revert changes in Data Anonymization article

examples/datamart/healthcheck.Rmd, examples/datamart/report_utils.R, python/pdstools/reports/HealthCheck.qmd
Some of the plots failed with many different configurations due to faceting issues - workaround provided, not a proper solution yet
=> Support some of the accounts with many more configurations

python/pdstools/reports/HealthCheck.qmd, python/pdstools/utils/cdh_utils.py
Fixed by just checking the indexing - still limited to 14 colors for channels by default
=> Fixed error when very many channels exist

python/pdstools/__init__.py, python/pdstools/adm/ADMDatamart.py, python/pdstools/prediction/Prediction.py, python/pdstools/prediction/__init__.py, python/pdstools/utils/cdh_utils.py, python/tests/test_ADMDatamart.py, python/tests/test_Prediction.py, python/tests/test_anonymizer.py, python/tests/test_cdh_utils.py
Summary functions on the ADM datamart class plus a skeleton Prediction class also with summary functions.
=> Introducing summary methods on ADM DM and a new Prediction class

python/pdstools/adm/ADMDatamart.py, python/pdstools/plots/plot_base.py, python/pdstools/plots/plots_plotly.py, python/pdstools/reports/HealthCheck.qmd, python/requirements.txt, python/tests/test_anonymizer.py, python/tests/test_cdh_utils.py
- Problem with Predictor Performance Heatmap sorting was resolved
- Response Count added to Treemap with Missing Value Percentages
- plotPredictorPerformance title is set to facet_val(e.g: configuration name). Prefix removed
- Upgraded to latest polars minor version
=> Maintenance for HealthCheck

.github/workflows/Python tests.yml
Upgraded codecov version to v4
=> Upgrade codecov

python/pdstools/pega_io/API.py
Fyi @yusufuyanik1  - I think you accidentally edited this to avoid a polars rename, but this was python code rather than Polars. No harm, but I've changed it back here.
=> Revert incorrect depcrecation

python/pdstools/utils/CDHLimits.py, python/tests/test_limits.py
Ready to be used in HC and x-cust dashboard
=> Included relevant limits and added some testing

examples/prediction_studio/Predictions.ipynb, python/pdstools/prediction/Prediction.py, python/pdstools/reports/HealthCheck.qmd, python/pdstools/reports/ModelReport.qmd, python/pdstools/utils/CDHLimits.py, python/requirements.txt, python/tests/test_healthcheck.py, python/tests/test_limits.py
Some helper code to analyse predictions data
=> Prediction analysis

python/pdstools/adm/BinAggregator.py, python/pdstools/adm/Tables.py, python/pdstools/plots/plots_plotly.py, python/pdstools/utils/cdh_utils.py, python/pdstools/utils/hds_utils.py, python/tests/test_ADMDatamart.py
Resolves #217
Also lumped in some non-functional but still useful changes to make a bunch of absolute imports (e.g. `from pdstools import ...`) relative (e.g. `from .. import cdh_utils`).
=> Gracefully handle empty data frame for extract_keys

python/pdstools/pega_io/Anonymization.py
Instead of using glob to list the temporary files we just collect them as they're being created
=> Minor changes to the anonymisation script

python/pdstools/adm/ADMDatamart.py, python/pdstools/reports/HealthCheck.qmd, python/pdstools/reports/ModelReport.qmd
Small bug on our end, using untyped date/time to backfill nulls in a column with other date/times.
=> Fixed timezone issue with new polars

examples/prediction_studio/Predictions.ipynb, python/pdstools/prediction/Prediction.py, python/pdstools/utils/cdh_utils.py, python/tests/test_Prediction.py
Adding test percentage and changed control percentage reporting to validate test/control setup better
=> Prediction fixes

examples/datamart/report_utils.R, python/pdstools/reports/HealthCheck.qmd
Refactored plot for volume per performance bin per channel as the ordering was inconsistent. Also cleaned up the code a bit.
=> Fixing issue with inconsitent coloring and ordering 

python/pdstools/adm/Aggregates.py, python/pdstools/adm/Plots.py, python/pdstools/adm/Reports.py, python/pdstools/reports/HealthCheck.qmd, python/pdstools/utils/cdh_utils.py, python/tests/test_healthcheck.py, python/tests/test_plots.py
- Added generate.excel function to export 3 datamart tables. [model_data, predictor_data(aggregated) and optional full predictor_data from last snapshot]
- removed kwargs from plots
- fixed some mypy warnings
=> Add generate_excel and fix mypy warnings

python/pdstools/reports/HealthCheck.qmd
Added try-except on 2 charts that failed with too many configurations.
=> avoid failing the report if one chart fails

python/pdstools/adm/ADMDatamart.py, python/pdstools/adm/Aggregates.py, python/pdstools/adm/Reports.py, python/pdstools/reports/HealthCheck.qmd, python/pdstools/reports/ModelReport.qmd, python/pdstools/utils/cdh_utils.py, python/pdstools/utils/report_utils.py, python/tests/test_Aggregates.py, python/tests/test_datasets.py, python/tests/test_end_to_end.py, python/tests/test_healthcheck.py
ADM summaries include status of AGB usage
=> Picking up ADM model type and using in summaries

python/pdstools/app/decision_analyzer/da_streamlit_utils.py, python/pdstools/app/decision_analyzer/pages/10_Business_Value_Analysis.py, python/pdstools/app/decision_analyzer/pages/3_Action_Distribution.py, python/pdstools/app/decision_analyzer/pages/6_Win_Loss_Analysis.py, python/pdstools/app/decision_analyzer/pages/8_Offer_Quality_Analysis.py, python/pdstools/app/health_check/Home.py, python/pdstools/app/health_check/pages/1_Data_Import.py, python/pdstools/utils/streamlit_utils.py
- Added quarto check to the first page of Health Check
- Persisting the selected import method and the datamart if the user changes pages and comes back to Data Import
- Removed redundant functions in Decision Analyzer utils.
=> app improvements

python/pdstools/adm/BinAggregator.py, python/pdstools/adm/Plots.py, python/pdstools/app/health_check/pages/3_Reports.py, python/pdstools/decision_analyzer/plots.py, python/pdstools/utils/streamlit_utils.py, python/pdstools/valuefinder/Plots.py, uv.lock
=> Remove PyArrow Dependency

examples/ih/Example_IH_Analysis.ipynb, python/pdstools/ih/IH.py
- Added get_sequences method to extract customer action sequences and outcomes
- Implemented calculate_pmi for computing PMI scores on bigrams and n-grams
- Added pmi_overview to summarize PMI data in a Polars DataFrame
- Updated notebook with "Interesting Pattern Analysis"
=> Add PMI-based pattern analysis to interaction history

examples/hds/hds_analysis.ipynb, python/pdstools/adm/ADMDatamart.py, python/pdstools/adm/Aggregates.py, python/pdstools/adm/CDH_Guidelines.py, python/pdstools/prediction/Prediction.py, python/pdstools/utils/cdh_utils.py, python/tests/test_Aggregates.py, python/tests/test_Prediction.py, python/tests/test_cdh_utils.py
Moved PDC data parsing into class methods in PDS tools
Generalized time parsing
=> Moved PDC data parsing into pdstools funcs

python/pdstools/adm/Aggregates.py
@operdeck, I noticed that these summaries produce a Null column for OmniChannel if there is no omnichannel information available. Even though the values should remain Null, having the column be a Null types makes the files incompatible for direct glob parquet scanning (as the schema doesn't match).
You can decide whether to merge this, but I think this is better :)
=> Cast omnichannel to floats

python/pdstools/__init__.py, python/pdstools/adm/Aggregates.py
The latest Polars version seems to require this
=> Set explicit return dtype in map_batches
